using System;
using System.Linq;
using System.Xml.Linq;
namespace SampleConApp
{
    class LinqSqlDemo
    {
        static void Main(string[] args)
        {
            // bulkinsertToDatabase();
            //readRecords();
            deleteRecord();
            readRecords();
            updateOperation();
        }

        private static void updateOperation()
        {
            throw new NotImplementedException("Do it urself!!!");
        }

        private static void deleteRecord()
        {
            var context = new PhoneBookDataContext();
            var selected = (from c in context.ContactTables where c.ContactName == "Thompson" select c).FirstOrDefault();
            if(selected == null)
            {
                Console.WriteLine("No record is found");
                return;
            }
            context.ContactTables.DeleteOnSubmit(selected);
            context.SubmitChanges();
        }

        private static void readRecords()
        {
            var context = new PhoneBookDataContext();
            var names = from c in context.ContactTables
                        select c.ContactName;
            foreach (var name in names) Console.WriteLine(name);
        }

        private static void bulkinsertToDatabase()
        {
            //Read the data of the XML Document and insert all the xmldata into the table of our database. 
            var context = new PhoneBookDataContext();//This class is autogenerated by the LINQ based on the name of the DBML File.
            var doc = XDocument.Load("PhoneBook.xml");
            var data = from element in doc.Descendants("Contact")
                       select new ContactTable
                       {
                           PhoneNo = Convert.ToInt64(element.Element("PhoneNo").Value),
                           ContactName = element.Element("Name").Value,
                           City  = element.Element("City").Value
                       };
            context.ContactTables.InsertAllOnSubmit(data);//Bulk Adding to the contacttables collection
            context.SubmitChanges();//Commit..
        }
    }
}