using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SampleConApp
{
    class Trainee
    {
        public int TraineeID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        //For defining the uniqueness of the object, we must override 2 methods of the System.Object which is the base class for all types in .NET
        public override int GetHashCode()
        {
            //hashCode is a unique id generated by the .NET Runtime when an object is created.
            return EmailAddress.GetHashCode();
        }

        public override bool Equals(object obj)
        {
            if (obj is Trainee) {
                //This will tell the equivalence of  the object.
                var temp = obj as Trainee;//Unboxing the object type...
                if ((EmailAddress == temp.EmailAddress) || (TraineeID == temp.TraineeID))
                    return true;
                else
                    return false;
            } else
                return false;//The objects are not same...

        }
    }
}
