//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTable
    {
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public long PhoneNo { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public decimal BillAmount { get; set; }
    }
}
